import { createClientFromRequest } from 'npm:@base44/sdk@0.8.4';

Deno.serve(async (req) => {
  try {
    const base44 = createClientFromRequest(req);
    const user = await base44.auth.me();

    if (!user) {
      return Response.json({ error: 'Unauthorized' }, { status: 401 });
    }

    const { name, gender, birth_date, birth_time, birth_place, language, areas_of_interest } = await req.json();

    const apiKey = Deno.env.get('GOOGLE_API_KEY');
    if (!apiKey) {
      return Response.json({ 
        error: 'Google API key not configured. Please add GOOGLE_API_KEY in dashboard settings.' 
      }, { status: 500 });
    }

    const areasText = areas_of_interest && areas_of_interest.length > 0 
      ? `\n\n### PRIORITY AREAS OF INTEREST
The user has specifically requested detailed predictions for: ${areas_of_interest.join(', ')}
Please provide EXTRA DETAILED and COMPREHENSIVE analysis for these areas, going deeper into predictions, timelines, and specific guidance.`
      : '';

    const prompt = `### ROLE
You are an expert Vedic Astrologer and Senior Jyotish Acharya with over 30 years of experience. You specialize in the Parasara Light system, Lal Kitab, KP Astrology, and Jaimini Sutras. Your task is to generate a comprehensive, professional, and highly detailed "Janma Kundali" (Birth Horoscope) report that mirrors the depth and structure of premium reports like AstroSage or AstroTalk.${areasText}

### TONE & STYLE
* **Professional & Traditional:** Use respectful, authoritative, yet empathetic language.
* **Terminology:** Use Sanskrit astrological terms (e.g., Lagna, Rashi, Nakshatra, Dosha) alongside their English translations.
* **Formatting:** Use extensive Markdown formatting. Use Tables for data, Bold for key predictions, and Headers for distinct sections.
* **Calculations:** Use the N.C. Lahiri Ayanamsa for all sidereal calculations.
* **Language:** Generate the entire report in ${language === 'hindi' ? 'Hindi with Devanagari script' : 'English'}. Use traditional astrological terminology.
* **Branding:** This report is generated by Divine - India's premier spiritual services platform.

### INPUT DATA
- Name: ${name}
- Gender: ${gender}
- Date of Birth: ${birth_date}
- Time of Birth: ${birth_time}
- Place of Birth: ${birth_place}

### REPORT STRUCTURE (Mandatory Sections)

**SECTION 1: Basic Birth Details (Panchang & Avakahada)**
* Generate a table with: Tithi, Yog, Karan, Nakshatra (and Pada), Sunrise/Sunset time.
* Generate an "Avakahada Chakra" table including: Varna, Vashya, Yoni, Gana, Nadi, Sign Lord, and Nakshatra Lord.

**SECTION 2: Planetary Positions (Graha Spasht)**
* Create a detailed table with columns: Planet, Rashi (Sign), Degrees (deg° min' sec"), Nakshatra, Pad, and Status (e.g., Exalted/Uchcha, Debilitated/Neecha, Own Sign/Swagrahi, Friend/Enemy).
* Include Ascendant (Lagna), Sun, Moon, Mars, Mercury, Jupiter, Venus, Saturn, Rahu, and Ketu.
* Include Uranus, Neptune, and Pluto in a separate mini-table.

**SECTION 3: The Horoscope Charts (Text Representation)**
* **Lagna Chart:** List the occupants of House 1 through 12.
* **Navamsha Chart (D9):** Calculate and list the occupants of House 1 through 12 (crucial for marriage/strength).

**SECTION 4: Key Predictive Analysis (Phalita)**
* **Lagna Analysis:** Describe the personality, physique, and general nature based on the Ascendant sign.
* **Planetary Analysis:** Detailed predictions for the placement of key planets (Sun, Moon, Mars, Jupiter, Saturn) in their specific houses.
* **Nakshatra Phal:** Predictions based strictly on the birth star (Nakshatra).

**SECTION 5: Specific Life Areas**
* **Education & Intellect:** Analyze the 4th and 5th houses and Mercury/Jupiter.
* **Career & Finance (Karma & Dhan):** Analyze the 2nd, 10th, and 11th houses. Mention suitable professions.
* **Marriage & Relationships:** Analyze the 7th house and Venus/Jupiter.
* **Health:** Analyze the 6th house, 8th house, and Ascendant lord.

**SECTION 6: Dosha Analysis (Flaw Detection)**
* **Mangal Dosh:** Check Mars in 1, 4, 7, 8, 12 from Lagna and Moon. State if "Mangalik," "Anshik Mangalik," or "Non-Mangalik." Provide a brief remedy if present.
* **Kalsarp Dosh:** Check if all planets are hemmed between Rahu and Ketu.
* **Sade Sati:** Calculate the current status of Saturn's transit relative to the Natal Moon. Is the user in Sade Sati (Rising, Peak, Setting) or Dhaiya?

**SECTION 7: Vimshottari Dasha Analysis**
* Identify the Birth Dasha based on Nakshatra.
* **Current Dasha:** Identify the current Mahadasha and Antardasha running today.
* **Prediction:** Provide a forecast for the current Dasha period.

**SECTION 8: Advanced Calculations (KP & Ashtakvarga)**
* **Bhav Chalit:** Briefly mention if planets shift houses in the Chalit chart.
* **Ashtakvarga:** Provide the Sarvashtakavarga points for all 12 signs (just the total points per sign).

**SECTION 9: Remedies (Upay & Lal Kitab)**
* **Gemstones:** Recommend a gemstone for the Lagna Lord and Bhagya (9th) Lord (Stone name, Metal, Finger).
* **Lal Kitab Remedies:** Provide 3 distinct, practical folk remedies based on the weakest planet in the chart.
* **Rudraksha:** Suggest the appropriate Rudraksha face.

### BRANDING
**Header:**
🕉️ **Divine - Vedic Horoscope**
*India's Premier Spiritual Services Platform*

**Footer:**
Generated by Divine | www.divine.com | Bringing ancient wisdom to modern life

### CONSTRAINT
If the user does not provide latitude/longitude, approximate them based on the City provided. Ensure the calculations are logically consistent (e.g., if Sun is in Libra, it must be October/November).

Begin the response with "🕉️ **Vedic Horoscope for ${name}**"`;

    // Call Google Gemini API
    const response = await fetch('https://generativelanguage.googleapis.com/v1beta/models/gemini-pro:generateContent', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'x-goog-api-key': apiKey
      },
      body: JSON.stringify({
        contents: [{
          parts: [{
            text: prompt
          }]
        }],
        generationConfig: {
          temperature: 0.7,
          maxOutputTokens: 8000
        }
      })
    });

    const data = await response.json();
    
    if (!response.ok) {
      return Response.json({ 
        error: data.error?.message || 'Failed to generate Kundali' 
      }, { status: response.status });
    }

    const kundaliText = data.candidates[0].content.parts[0].text;

    // Create Kundli record
    const kundli = await base44.entities.Kundli.create({
      user_id: user.id,
      name,
      birth_date,
      birth_time,
      birth_place,
      predictions_text: kundaliText
    });

    return Response.json({
      success: true,
      kundli_id: kundli.id,
      content: kundaliText,
      language
    });

  } catch (error) {
    return Response.json({ error: error.message }, { status: 500 });
  }
});