import { createClientFromRequest } from 'npm:@base44/sdk@0.8.4';

Deno.serve(async (req) => {
  try {
    const base44 = createClientFromRequest(req);
    const user = await base44.auth.me();

    if (!user) {
      return Response.json({ error: 'Unauthorized' }, { status: 401 });
    }

    const { name, gender, birth_date, birth_time, birth_place, latitude, longitude, timezone_str, language, areas_of_interest } = await req.json();

    const freeAstrologyApiKey = Deno.env.get('FREEASTROLOGYAPI_KEY');
    if (!freeAstrologyApiKey) {
      return Response.json({ 
        error: 'Free Astrology API key not configured. Please add FREEASTROLOGYAPI_KEY in dashboard settings.' 
      }, { status: 500 });
    }

    const googleApiKey = Deno.env.get('GOOGLE_API_KEY');
    if (!googleApiKey) {
      return Response.json({ 
        error: 'Google API key not configured.' 
      }, { status: 500 });
    }

    // Parse birth date and time
    const [year, month, day] = birth_date.split('-').map(Number);
    const [hours, minutes] = birth_time.split(':').map(Number);

    // Get astrological data from freeastrologyapi.com
    const astrologyApiResponse = await fetch('https://json.freeastrologyapi.com/planets', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'x-api-key': freeAstrologyApiKey
      },
      body: JSON.stringify({
        year: year,
        month: month,
        date: day,
        hours: hours,
        minutes: minutes,
        seconds: 0,
        latitude: latitude,
        longitude: longitude,
        timezone: parseFloat(timezone_str),
        settings: {
          observation_point: "topocentric",
          ayanamsha: "lahiri"
        }
      })
    });

    const astrologyData = await astrologyApiResponse.json();

    if (!astrologyApiResponse.ok) {
      return Response.json({ 
        error: astrologyData.message || 'Failed to get astrological data from API',
        details: astrologyData
      }, { status: astrologyApiResponse.status });
    }

    const areasText = areas_of_interest && areas_of_interest.length > 0 
      ? `\n\n### PRIORITY AREAS OF INTEREST
The user has specifically requested detailed predictions for: ${areas_of_interest.join(', ')}
Please provide EXTRA DETAILED and COMPREHENSIVE analysis for these areas, going deeper into predictions, timelines, and specific guidance.`
      : '';

    const prompt = `### ROLE
You are an expert Vedic Astrologer and Senior Jyotish Acharya with over 30 years of experience. You specialize in the Parasara Light system, Lal Kitab, KP Astrology, and Jaimini Sutras. Your task is to generate a comprehensive, professional, and highly detailed "Janma Kundali" (Birth Horoscope) report that mirrors the depth and structure of premium reports like AstroSage or AstroTalk.${areasText}

### TONE & STYLE
* **Professional & Traditional:** Use respectful, authoritative, yet empathetic language.
* **Terminology:** Use Sanskrit astrological terms (e.g., Lagna, Rashi, Nakshatra, Dosha) alongside their English translations.
* **Formatting:** Use extensive Markdown formatting. Use Tables for data, Bold for key predictions, and Headers for distinct sections.
* **Language:** Generate the entire report in ${language === 'hindi' ? 'Hindi with Devanagari script' : 'English'}. Use traditional astrological terminology.
* **Branding:** This report is generated by Divine - India's premier spiritual services platform.

### INPUT DATA
- Name: ${name}
- Gender: ${gender}
- Date of Birth: ${birth_date}
- Time of Birth: ${birth_time}
- Place of Birth: ${birth_place}
- Latitude: ${latitude}
- Longitude: ${longitude}
- Timezone: ${timezone_str}

### ASTROLOGICAL DATA (from freeastrologyapi.com)
${JSON.stringify(astrologyData, null, 2)}

### REPORT STRUCTURE (Mandatory Sections)

**SECTION 1: Basic Birth Details (Panchang & Avakahada)**
* Use the provided astrological data to create a table with: Tithi, Yog, Karan, Nakshatra (and Pada), Sunrise/Sunset time.
* Generate an "Avakahada Chakra" table including: Varna, Vashya, Yoni, Gana, Nadi, Sign Lord, and Nakshatra Lord.

**SECTION 2: Planetary Positions (Graha Spasht)**
* Create a detailed table with columns: Planet, Rashi (Sign), Degrees, Nakshatra, Pad, and Status (e.g., Exalted/Uchcha, Debilitated/Neecha, Own Sign/Swagrahi).
* Use the planetary data provided from the API.
* Include Ascendant (Lagna), Sun, Moon, Mars, Mercury, Jupiter, Venus, Saturn, Rahu, and Ketu.

**SECTION 3: The Horoscope Charts (Text Representation)**
* **Lagna Chart:** List the occupants of House 1 through 12.
* **Navamsha Chart (D9):** List the occupants of House 1 through 12 (crucial for marriage/strength).

**SECTION 4: Key Predictive Analysis (Phalita)**
* **Lagna Analysis:** Describe the personality, physique, and general nature based on the Ascendant sign.
* **Planetary Analysis:** Detailed predictions for the placement of key planets (Sun, Moon, Mars, Jupiter, Saturn) in their specific houses.
* **Nakshatra Phal:** Predictions based strictly on the birth star (Nakshatra).

**SECTION 5: Specific Life Areas**
* **Education & Intellect:** Analyze the 4th and 5th houses and Mercury/Jupiter.
* **Career & Finance (Karma & Dhan):** Analyze the 2nd, 10th, and 11th houses. Mention suitable professions.
* **Marriage & Relationships:** Analyze the 7th house and Venus/Jupiter.
* **Health:** Analyze the 6th house, 8th house, and Ascendant lord.

**SECTION 6: Dosha Analysis (Flaw Detection)**
* **Mangal Dosh:** Check Mars in 1, 4, 7, 8, 12 from Lagna and Moon. State if "Mangalik," "Anshik Mangalik," or "Non-Mangalik." Provide a brief remedy if present.
* **Kalsarp Dosh:** Check if all planets are hemmed between Rahu and Ketu.
* **Sade Sati:** Calculate the current status of Saturn's transit relative to the Natal Moon.

**SECTION 7: Vimshottari Dasha Analysis**
* Identify the Birth Dasha based on Nakshatra.
* **Current Dasha:** Identify the current Mahadasha and Antardasha running today.
* **Prediction:** Provide a forecast for the current Dasha period.

**SECTION 8: Remedies (Upay & Lal Kitab)**
* **Gemstones:** Recommend a gemstone for the Lagna Lord and Bhagya (9th) Lord (Stone name, Metal, Finger).
* **Lal Kitab Remedies:** Provide 3 distinct, practical folk remedies based on the weakest planet in the chart.
* **Rudraksha:** Suggest the appropriate Rudraksha face.

### BRANDING
**Header:**
🕉️ **Divine - Vedic Horoscope**
*India's Premier Spiritual Services Platform*

**Footer:**
Generated by Divine | www.divine.com | Bringing ancient wisdom to modern life

Begin the response with "🕉️ **Vedic Horoscope for ${name}**"`;
    
    // Call Google Gemini API to interpret astrological data
    const response = await fetch('https://generativelanguage.googleapis.com/v1/models/gemini-1.5-pro-latest:generateContent', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'x-goog-api-key': googleApiKey
      },
      body: JSON.stringify({
        contents: [{
          parts: [{
            text: prompt
          }]
        }],
        generationConfig: {
          temperature: 0.7,
          maxOutputTokens: 8000
        }
      })
    });

    const data = await response.json();
    
    if (!response.ok) {
      return Response.json({ 
        error: data.error?.message || 'Failed to generate Kundali',
        details: data
      }, { status: response.status });
    }

    const kundaliText = data.candidates[0].content.parts[0].text;

    // Create Kundli record
    const kundli = await base44.entities.Kundli.create({
      user_id: user.id,
      name,
      birth_date,
      birth_time,
      birth_place,
      latitude,
      longitude,
      timezone_str,
      astrological_data: astrologyData,
      predictions_text: kundaliText
    });

    return Response.json({
      success: true,
      kundli_id: kundli.id,
      content: kundaliText,
      language
    });

  } catch (error) {
    return Response.json({ 
      error: error.message,
      stack: error.stack 
    }, { status: 500 });
  }
});