import React, { useState } from 'react';
import { useQuery } from '@tanstack/react-query';
import { base44 } from '@/api/base44Client';
import { Card } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Sparkles, Calendar, MapPin, Eye, Trash2, Search, Loader2 } from 'lucide-react';
import { Link } from 'react-router-dom';
import { createPageUrl } from '@/utils';
import moment from 'moment';
import { toast } from 'sonner';
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
} from "@/components/ui/dialog";
import ReactMarkdown from 'react-markdown';
import { jsPDF } from 'jspdf';
import BackButton from '../components/ui/BackButton';

export default function MyKundalis() {
  const [searchQuery, setSearchQuery] = useState('');
  const [selectedKundli, setSelectedKundli] = useState(null);

  const { data: kundalis = [], isLoading, refetch } = useQuery({
    queryKey: ['my-kundalis'],
    queryFn: async () => {
      const user = await base44.auth.me();
      return base44.entities.Kundli.filter({ user_id: user.id, is_deleted: false }, '-created_date');
    }
  });

  const handleDelete = async (kundliId) => {
    if (!confirm('Are you sure you want to delete this Kundali?')) return;
    
    try {
      await base44.entities.Kundli.update(kundliId, { is_deleted: true });
      toast.success('Kundali deleted successfully');
      refetch();
    } catch (error) {
      toast.error('Failed to delete Kundali');
    }
  };

  const downloadPDF = (kundli) => {
    const doc = new jsPDF();
    const pageWidth = doc.internal.pageSize.getWidth();
    const pageHeight = doc.internal.pageSize.getHeight();
    const margin = 20;
    const maxLineWidth = pageWidth - 2 * margin;
    let yPosition = margin;

    // Header
    doc.setFillColor(255, 153, 0);
    doc.rect(0, 0, pageWidth, 30, 'F');
    doc.setTextColor(255, 255, 255);
    doc.setFontSize(20);
    doc.text('🕉️ Divine', margin, 15);
    doc.setFontSize(10);
    doc.text('Vedic Horoscope Report', margin, 23);
    
    yPosition = 40;
    doc.setTextColor(0, 0, 0);

    // Personal Details
    doc.setFontSize(14);
    doc.setFont(undefined, 'bold');
    doc.text('Personal Details', margin, yPosition);
    yPosition += 10;

    doc.setFontSize(10);
    doc.setFont(undefined, 'normal');
    doc.text(`Name: ${kundli.name}`, margin, yPosition);
    yPosition += 7;
    doc.text(`Birth Date: ${kundli.birth_date}`, margin, yPosition);
    yPosition += 7;
    doc.text(`Birth Time: ${kundli.birth_time}`, margin, yPosition);
    yPosition += 7;
    doc.text(`Birth Place: ${kundli.birth_place}`, margin, yPosition);
    yPosition += 10;

    // Content
    const lines = doc.splitTextToSize(kundli.predictions_text, maxLineWidth);
    
    lines.forEach(line => {
      if (yPosition > pageHeight - margin) {
        doc.addPage();
        yPosition = margin;
      }
      doc.text(line, margin, yPosition);
      yPosition += 7;
    });

    // Footer
    const totalPages = doc.internal.getNumberOfPages();
    for (let i = 1; i <= totalPages; i++) {
      doc.setPage(i);
      doc.setFontSize(8);
      doc.setTextColor(128, 128, 128);
      doc.text(
        `Generated by Divine | Page ${i} of ${totalPages}`,
        pageWidth / 2,
        pageHeight - 10,
        { align: 'center' }
      );
    }

    doc.save(`Kundali_${kundli.name.replace(/\s+/g, '_')}_${kundli.created_date.split('T')[0]}.pdf`);
    toast.success('PDF downloaded successfully!');
  };

  const filteredKundalis = kundalis.filter(k => 
    k.name.toLowerCase().includes(searchQuery.toLowerCase()) ||
    k.birth_place.toLowerCase().includes(searchQuery.toLowerCase())
  );

  return (
    <div className="min-h-screen bg-gradient-to-br from-orange-50 via-white to-amber-50 pb-24">
      <div className="container mx-auto px-4 py-8 max-w-6xl">
        <BackButton />

        <div className="mb-8">
          <div className="flex items-center gap-3 mb-4">
            <div className="w-16 h-16 bg-gradient-to-r from-orange-500 to-amber-500 rounded-full flex items-center justify-center">
              <Sparkles className="w-8 h-8 text-white" />
            </div>
            <div>
              <h1 className="text-4xl font-bold text-gray-900">My Kundalis</h1>
              <p className="text-gray-600">View and manage your saved horoscope reports</p>
            </div>
          </div>

          <div className="flex gap-4 items-center">
            <div className="relative flex-1">
              <Search className="absolute left-3 top-1/2 transform -translate-y-1/2 text-gray-400 w-5 h-5" />
              <Input
                placeholder="Search by name or birth place..."
                value={searchQuery}
                onChange={(e) => setSearchQuery(e.target.value)}
                className="pl-10"
              />
            </div>
            <Link to={createPageUrl('KundliGenerator')}>
              <Button className="bg-orange-500 hover:bg-orange-600">
                <Sparkles className="w-4 h-4 mr-2" />
                Generate New
              </Button>
            </Link>
          </div>
        </div>

        {isLoading ? (
          <div className="flex justify-center items-center py-20">
            <Loader2 className="w-8 h-8 animate-spin text-orange-500" />
          </div>
        ) : filteredKundalis.length === 0 ? (
          <Card className="p-12 text-center">
            <Sparkles className="w-16 h-16 text-gray-300 mx-auto mb-4" />
            <h3 className="text-xl font-semibold text-gray-700 mb-2">
              {searchQuery ? 'No matching Kundalis found' : 'No Kundalis yet'}
            </h3>
            <p className="text-gray-500 mb-6">
              {searchQuery 
                ? 'Try a different search term' 
                : 'Generate your first Vedic horoscope to get started'}
            </p>
            {!searchQuery && (
              <Link to={createPageUrl('KundliGenerator')}>
                <Button className="bg-orange-500 hover:bg-orange-600">
                  <Sparkles className="w-4 h-4 mr-2" />
                  Generate Kundali
                </Button>
              </Link>
            )}
          </Card>
        ) : (
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
            {filteredKundalis.map((kundli) => (
              <Card key={kundli.id} className="p-6 hover:shadow-lg transition-shadow">
                <div className="flex items-start justify-between mb-4">
                  <div className="flex-1">
                    <h3 className="text-xl font-bold text-gray-900 mb-1">{kundli.name}</h3>
                    <div className="space-y-1 text-sm text-gray-600">
                      <div className="flex items-center gap-2">
                        <Calendar className="w-4 h-4" />
                        <span>{kundli.birth_date} at {kundli.birth_time}</span>
                      </div>
                      <div className="flex items-center gap-2">
                        <MapPin className="w-4 h-4" />
                        <span>{kundli.birth_place}</span>
                      </div>
                    </div>
                  </div>
                </div>

                {kundli.rashi && (
                  <div className="mb-4 p-3 bg-orange-50 rounded-lg">
                    <p className="text-xs text-gray-600">Rashi</p>
                    <p className="font-semibold text-orange-700">{kundli.rashi}</p>
                  </div>
                )}

                <div className="text-xs text-gray-500 mb-4">
                  Generated {moment(kundli.created_date).fromNow()}
                </div>

                <div className="flex gap-2">
                  <Button
                    variant="outline"
                    size="sm"
                    className="flex-1"
                    onClick={() => setSelectedKundli(kundli)}
                  >
                    <Eye className="w-4 h-4 mr-1" />
                    View
                  </Button>
                  <Button
                    variant="outline"
                    size="sm"
                    onClick={() => downloadPDF(kundli)}
                  >
                    Download
                  </Button>
                  <Button
                    variant="ghost"
                    size="sm"
                    onClick={() => handleDelete(kundli.id)}
                    className="text-red-500 hover:text-red-700 hover:bg-red-50"
                  >
                    <Trash2 className="w-4 h-4" />
                  </Button>
                </div>
              </Card>
            ))}
          </div>
        )}

        {/* View Dialog */}
        <Dialog open={!!selectedKundli} onOpenChange={() => setSelectedKundli(null)}>
          <DialogContent className="max-w-4xl max-h-[80vh] overflow-y-auto">
            <DialogHeader>
              <DialogTitle className="text-2xl">
                🕉️ {selectedKundli?.name}'s Kundali
              </DialogTitle>
            </DialogHeader>
            
            {selectedKundli && (
              <div>
                <div className="bg-gradient-to-r from-orange-500 to-amber-500 text-white p-6 rounded-lg mb-6">
                  <div className="grid grid-cols-2 gap-4 text-sm">
                    <div>
                      <p className="opacity-80">Birth Date</p>
                      <p className="font-semibold">{selectedKundli.birth_date}</p>
                    </div>
                    <div>
                      <p className="opacity-80">Birth Time</p>
                      <p className="font-semibold">{selectedKundli.birth_time}</p>
                    </div>
                    <div className="col-span-2">
                      <p className="opacity-80">Birth Place</p>
                      <p className="font-semibold">{selectedKundli.birth_place}</p>
                    </div>
                  </div>
                </div>

                <div className="prose prose-orange max-w-none">
                  <ReactMarkdown
                    components={{
                      h1: ({ children }) => (
                        <h1 className="text-2xl font-bold text-orange-600 mt-6 mb-3 pb-2 border-b-2 border-orange-200">
                          {children}
                        </h1>
                      ),
                      h2: ({ children }) => (
                        <h2 className="text-xl font-bold text-orange-700 mt-4 mb-2">
                          {children}
                        </h2>
                      ),
                      table: ({ children }) => (
                        <div className="overflow-x-auto my-4">
                          <table className="min-w-full border-collapse border border-gray-300 text-sm">
                            {children}
                          </table>
                        </div>
                      ),
                      th: ({ children }) => (
                        <th className="border border-gray-300 bg-orange-100 px-3 py-2 text-left font-semibold">
                          {children}
                        </th>
                      ),
                      td: ({ children }) => (
                        <td className="border border-gray-300 px-3 py-2">
                          {children}
                        </td>
                      ),
                    }}
                  >
                    {selectedKundli.predictions_text}
                  </ReactMarkdown>
                </div>
              </div>
            )}
          </DialogContent>
        </Dialog>
      </div>
    </div>
  );
}